---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prem-capstone
  labels:
    app: prem-capstone
  namespace: default
spec:
  selector:
    matchLabels:
      app: prem-capstone
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
      maxSurge: 30%
  template:
    metadata:
      labels:
        app: prem-capstone
    spec:
      containers:
      - name: prem-capstone
        image: 467723919671.dkr.ecr.us-east-1.amazonaws.com/prem-capstone
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prem-capstone-service
spec:
  selector:
    app: prem-capstone
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80